// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLBWONW925uCcfcJS_ZwQCs3qkPwFWsq0',
    appId: '1:2948084702:web:ba7d86ecab58c25b2ea34f',
    messagingSenderId: '2948084702',
    projectId: 'na-app-4104a',
    authDomain: 'na-app-4104a.firebaseapp.com',
    storageBucket: 'na-app-4104a.firebasestorage.app',
    measurementId: 'G-HH9RP88ZBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwHQlgHBk0dXC_SMRnedNfcdKKV8tuy9Y',
    appId: '1:2948084702:android:855861e05a6f7ca02ea34f',
    messagingSenderId: '2948084702',
    projectId: 'na-app-4104a',
    storageBucket: 'na-app-4104a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG3CJRRmxbXVX0ytEu24jyjeTuuUYKRVc',
    appId: '1:2948084702:ios:e97cfeb85c1ed9c92ea34f',
    messagingSenderId: '2948084702',
    projectId: 'na-app-4104a',
    storageBucket: 'na-app-4104a.firebasestorage.app',
    iosBundleId: 'com.example.naApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG3CJRRmxbXVX0ytEu24jyjeTuuUYKRVc',
    appId: '1:2948084702:ios:e97cfeb85c1ed9c92ea34f',
    messagingSenderId: '2948084702',
    projectId: 'na-app-4104a',
    storageBucket: 'na-app-4104a.firebasestorage.app',
    iosBundleId: 'com.example.naApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLBWONW925uCcfcJS_ZwQCs3qkPwFWsq0',
    appId: '1:2948084702:web:17f497c386995b0c2ea34f',
    messagingSenderId: '2948084702',
    projectId: 'na-app-4104a',
    authDomain: 'na-app-4104a.firebaseapp.com',
    storageBucket: 'na-app-4104a.firebasestorage.app',
    measurementId: 'G-78C686SZCG',
  );
}
